#!/bin/bash

# Copyright (C) 2015 Benjamin Abendroth
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

################################################################################
# Filesystem functions #########################################################
################################################################################

# regular functions ############################################################
dir_exists () {
  [[ -d "$1" ]]
}

dir_is_readable () {
  [[ -d "$1" ]] && [[ -r "$1" ]] && [[ -x "$1" ]]
}

dir_is_writable () {
  [[ -d "$1" ]] && [[ -w "$1" ]]
}

file_exists () {
  [[ -f "$1" ]]
}

file_is_readable () {
  [[ -f "$1" ]] && [[ -r "$1" ]]
}

file_is_writable () {
  [[ -f "$1" ]] && [[ -w "$1" ]]
}

# other functions ##############################################################
is_empty_dir () {
  [[ -d "$1" ]] && [[ -x "$1" ]] && [[ -z "`ls -A "$1"`"  ]]
}

is_empty_file () {
  [[ -f "$1" ]] && [[ -r "$1" ]] && [[ -z "`<$1`" ]]
}

is_same_file () {
  diff -q "$1" "$2" >/dev/null 2>&1
}
