#!/bin/bash

# Copyright (C) 2015 Benjamin Abendroth
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

################################################################################
# Process functions ############################################################
################################################################################

num_procs () {
  local PROC_NAME="${1:?$FUNCNAME: Missing argument}"
  pidof -x "$PROC_NAME" | wc -w
}

wait_for () {
  local PROC_NAME="${1:?$FUNCNAME: Missing argument}"

  while pidof -x "$PROC_NAME" &>/dev/null ; do
    sleep 0.5
  done
}

function start () {
  killall -CONT "$@"
}

function stop () {
  killall -STOP "$@"
}
