#!/bin/bash

# Copyright (C) 2015 Benjamin Abendroth
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

################################################################################
# Scripting functions ##########################################################
################################################################################

basename_file () {
  echo "${0##*/}"
}

progname () {
  echo "${0##*/}" | sed 's/\.sh$//g'
}

log () {
  echo "[`date '+%b %d %H:%M:%S'`] $PROGNAME: $*" | tee -a ${LOGFILE:-/dev/null} >&2
}

clean () {
  local VAR=""

  for VAR in "${!TEMP_@}" "${!TMP_@}" ; do
    rm -rf "${!VAR}"
  done
}

die () {
  clean
  DIE=${1:-$DIE}
  exit ${DIE:-0}
}

signal_die () {
  echo "$PROGNAME: Exiting: recieved SIG$1" >&2
  die
}

check_dependencies () {
  local DEP="" RETURN=0 PROG="" PACKAGE=""

  for DEP in "$@" ; do
    PROG="${DEP%%:*}"
    PACKAGE="${DEP##*:}"
    if ! which -- $PROG &>/dev/null ; then
      printf "$PROGNAME: Program \"$PROG\" not found in \$PATH" >&2

      if [[ "$PACKAGE" != "$PROG" ]] ; then
        printf " [can be found in the '$PACKAGE' package]" >&2
      fi

      printf "\n" >&2

      RETURN=1
    fi
  done

  return $RETURN
}

check_root () {
  if [[ $UID != 0 ]] ; then
    echo "$PROGNAME: Needs to be run as root" >&2
    return 1
  fi
}

secure_script () {
  chmod go-rw "$0"
}

PROGNAME=`progname`
