#!/bin/bash

# Copyright (C) 2015 Benjamin Abendroth
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

################################################################################
# trap: signal_die #############################################################
################################################################################

trap 'signal_die INT'  INT
trap 'signal_die TERM' TERM
trap 'signal_die QUIT' QUIT
trap 'signal_die KILL' KILL
trap 'signal_die HUP'  HUP
trap 'die' 0 # normal exit
